dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}